#!/bin/bash
## Octave-Forge: video package bootstrap script
## Run this to generate the configure script

set -e      # halt if unhandled error
aclocal
autoconf    # generate configure script
autoheader -f
rm -rf autom4te.cache
