sinclude ./Makeconf

all: ../bin/ofsndplay

## Using explicit -ObjC flag since .cc is used to trick PKG_ADD to
## pick up the file as a CPP file.
../bin/ofsndplay: OFSndPlay.cc
	mkdir -p ../bin
	$(CC) -ObjC -o ../bin/ofsndplay OFSndPlay.cc -framework Cocoa
